### ISSUE TITLE
Update Docs How To Enable Debug Mode

### ISSUE THREAD

**Issue by brianpham** [fjogeleit/yaml-update-action#111]
I am seeing this error when trying the action `Error: HttpError: Not Found` and trying to debug a bit more. I see that there is an option to enable debug mode, but not sure how to do that.

**Comment by brianpham** [comment]
Nvm, I thought there was an option I had to set for this specific action. It is actually this https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging

**Comment by ionutzp** [comment]
this should be added to the docs, it is indeed unclear, i was searching in the code for a `debug` option

**Comment by fjogeleit** [comment]
Thanks for remembering, I’ll take a look on it.
