### ISSUE TITLE
can not access github actions workflow yaml files path

### ISSUE THREAD

**Issue by christian-draeger** [fjogeleit/yaml-update-action#113]
i have a github actions workflow to automatically publish a library by manual trigger.

here is my workflow yaml: https://github.com/skrapeit/skrape.it/blob/master/.github/workflows/release.yml

since it is a dispatch workflow with input field i want to use your action to set the default input value to the latest release version of my project.

here is my build: https://github.com/skrapeit/skrape.it/runs/2249136461?check_suite_focus=true#step:10:1
it says:
```
Run fjogeleit/yaml-update-action@v0.2.1
  with:
    valueFile: .github/workflows/release.yaml
    propertyPath: on.workflow_dispatch.inputs.version.default
    commitChange: false
    value: 0.0.3
    branch: master
    targetBranch: master
    createPR: false
    token: ***
    repository: skrapeit/skrape.it
    workDir: .
  env:
    JAVA_HOME_8.0.282_x64: /opt/hostedtoolcache/jdk/8.0.282/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.282/x64
    JAVA_HOME_8_0_282_X64: /opt/hostedtoolcache/jdk/8.0.282/x64
Error: Error: could not parse file with path: /home/runner/work/skrape.it/skrape.it/.github/workflows/release.yaml
```

it looks like it is not able to access the following path `.github/workflows/release.yml`

**Comment by fjogeleit** [comment]
Hey, I tried it myself and did a `ls -l` in my workflow. It looks like that by default the `.github` folder is not present in actions.

You can try it yourself by running:

```yaml
jobs:
  check: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls -l
```

**Comment by christian-draeger** [comment]
since it has a `.` as prefix it will be treated as hidden file/folder. thats why `ls -l` is not showing it.
```
# partial man page of ls

-l               -       use a long listing format
-a, --all     -      do not ignore entries starting with .
```

i tried it with `ls -la` which shows that it is included in the workspace :) (https://github.com/skrapeit/skrape.it/runs/2252665993?check_suite_focus=true#step:3:8)

**Comment by fjogeleit** [comment]
Okay, then I will have a deeper look ;-)

**Comment by christian-draeger** [comment]
hey i found it haha. sorry for inconvenience. i messed up the file type and referenced `.yaml` in my workflow but my actual workflow file ends with `.yml` 😅🤦🏻‍♂️

but one last question: in my example i am using the yaml-update-action to update the value `on.workflow_dispatch.inputs.version.default` of a certain yaml file with the string 'works'.
but it doesnt seem to work. in my exampke i am printing the yaml, update it, and print it  again. when printing the file afterwards the value is not set. 

workflow: https://github.com/skrapeit/skrape.it/blob/master/.github/workflows/debug-workspace.yml
test run that show-cases behavior: https://github.com/skrapeit/skrape.it/runs/2252894321?check_suite_focus=true#step:6:11

**Comment by fjogeleit** [comment]
Okay great, hm the current implementation did not change the current file, it commits an InMemory updated copy of the file. I have a look today if I can add a new configuration to update the actual file in your workflow.

**Comment by fjogeleit** [comment]
I added a new action input "updateFile". This property is default false. You can set it to true and the action will update your file.

See https://github.com/fjogeleit/yaml-update-action/runs/2253257376?check_suite_focus=true#step:5:14 for reference

**Comment by christian-draeger** [comment]
Works like a charm. Vielen Dank ✌️

**Comment by fjogeleit** [comment]
nice to hear. Gern geschehen :-)
