### ISSUE TITLE
Feature Request: Ability to skip commit

### ISSUE THREAD

**Issue by chrisjohnson00** [fjogeleit/yaml-update-action#13]
I have a use case where I need to update multiple property paths in the same file.
As it is, it works, but generates a commit for each update.  
If you could implement a "no commit" flag then I could use `stefanzweifel/git-auto-commit-action@v4` to manage committing the changes as a single commit instead of multiple.

Thanks for the nice action!

**Comment by fjogeleit** [comment]
Hey, thanks for your feedback Glad that this Action helps you.

I added a new Input argument "commitChange" that is set to true by default. So the default behavior is the same. You can set this input to "false" to disable the commit and push part. I also set defaults for git related required inputs. So you can skip them.

If there is any problem or it did not work as expected please let me now.
