### ISSUE TITLE
Feature request: custom PR title & labels. Custom git committer?

### ISSUE THREAD

**Issue by cenobitedk** [fjogeleit/yaml-update-action#130]
Thanks for a great action!

I would love to be able to customise the created PR title and the labels that are added. 
The PR title could just be a custom prefix for the commit message, the hardcoded "Merge: " is not a fit for all.

Also, would it be possible to customise the git committer? or is it bound to the token/PAT token?

**Comment by fjogeleit** [comment]
Hey, thanks for your request and feedback.

I will have a look on the title and labels, that should be no big deal.

The committer depends on your Token, if you use the default token it is the Github bot, if you use a custom token it is the creator of the token.

**Comment by cenobitedk** [comment]
@fjogeleit Thanks for the reply

**Comment by fjogeleit** [comment]
You can try the new release https://github.com/fjogeleit/yaml-update-action/releases/tag/v0.4.0 with a new title and labels option to customize the behavior as you want. Let me know if it works as expected or if I miss something.
