### ISSUE TITLE
Correct propertyPath syntax for list members?

### ISSUE THREAD

**Issue by plzm** [fjogeleit/yaml-update-action#155]
I have a YAML file with a structure like this (using periods to denote spaces in YAML as github editor removes visual indentation when using spaces in the below)

spec
..template
....spec
......containers
......- name: container1
........image: FOO

I am not able to replace FOO with these different attempts at propertyPath:
spec.template.spec.containers.image
spec.template.spec.containers[0].image
spec.template.spec.containers{0}.image

Could you please specify the correct syntax to modify a list member like FOO in the above? Thank you!

**Comment by fjogeleit** [comment]
Hey, currently it supports only the JS dot notation.

In your example the path would be `spec.template.spec.containers.0.image`

**Comment by plzm** [comment]
Perfect, that works - thank you!
