### ISSUE TITLE
Feature request: update multiple files

### ISSUE THREAD

**Issue by cenobitedk** [fjogeleit/yaml-update-action#173]
Again, thanks for a great action!

It seem typical to have 1 `values.yaml` file, but in order to avoid overrides for multiple environments it is possible to use multiple files, e.g. `values-test.yaml`, `values-staging.yaml` and `values-prod.yaml`. This moves more or less all config into the repository with version history. Very GitOps :)

However, the action only allow a single file to be updated, so I was wondering if it would be possible to create support for multiple files, each with `valueFile`, `propertyPath` and `value`? 

If it's not possible to update multiple files, then maybe you can advise how to update them in multiple steps with the last step creating the PR as well?

**Comment by fjogeleit** [comment]
Hey @cenobitedk, thank you.

This is already possible with the current version. You can commit each change and create the PR with the last update.

I created an example of this approach in the test workflow:

https://github.com/fjogeleit/yaml-update-action/blob/master/.github/workflows/test.yml#L66

https://github.com/fjogeleit/yaml-update-action/runs/2808547282?check_suite_focus=true

The PR looks like this:

https://github.com/fjogeleit/yaml-update-action/pull/177

I hope this works for you.

**Comment by cenobitedk** [comment]
Ah, that's great! Thank you for the guidance and examples! 👏

**Comment by fjogeleit** [comment]
Glad to help you
