### ISSUE TITLE
Feature request: PR description

### ISSUE THREAD

**Issue by cenobitedk** [fjogeleit/yaml-update-action#182]
Hello again ;-)

Is it possible to add description to the pull request?
Currently I'm using this when repo A updates (merge), then it commits the new tag to repo B (helm charts) and create a PR, but in the created PR there's no reference to the merge commit in repo A (or could be a release as well).
Is it possible to add description to the PR creation?

**Comment by fjogeleit** [comment]
Hey, thanks for you request. I will check the APIs if this is possible.

**Comment by fjogeleit** [comment]
You can use "description" as new optional input to describe your PR. Its available in version v0.5.0 or latest.

**Comment by cenobitedk** [comment]
Thanks! This is great! 🥇
