### ISSUE TITLE
Empty Space throws Lexical error in v0.7.0

### ISSUE THREAD

**Issue by dungi** [fjogeleit/yaml-update-action#428]
Hey,

I used v0.7.0 to update a value in YML. Example:

```
configs:
 My Value: 4
```

If I write propertyPath like this: `'configs.${{ github.event.inputs.key }}'`
where key is 'My Value'

works good on v0.6.0 - but not anymore in v0.7.0

**Comment by fjogeleit** [comment]
hey, thanks for reporting. in v0.7 I switched to jsonpath instead of the custom implementation. I will have a look on it and how I can fix it. So you don't miss anything if you use v0.6 until I fixed this issue.

**Comment by fjogeleit** [comment]
Can you try the following syntax alternative: `'configs["${{ github.event.inputs.key }}"]'` ?

**Comment by dungi** [comment]
Working with 0.7 `'configs["${{ github.event.inputs.key }}"]'` works for me now.

**Comment by fjogeleit** [comment]
Great, Thanks for your feedback. So I close the issue, let me no if you have further problems.
