### ISSUE TITLE
Error when PropertyPath contains hyphens

### ISSUE THREAD

**Issue by NabilCC** [fjogeleit/yaml-update-action#433]
Hi there,

We have just started noticing an issue when the YAML update plugin throws an error when the value for `propertyPath` contains a hyphen (for example: `services.my-service.build-no`):

```shell
Error: Error: Lexical error on line 1. Unrecognized text.
$.services.my-service.build-no
--------------^
```

This issue seems to have been introduced recently, since our pipelines have been working up until now when using hyphens.

Many thanks in advance for any assistance you can offer!

**Comment by fjogeleit** [comment]
Hey thanks for reporting, yes. This issue is caused by the switch from my custom implementation to jsonpath in v0.7.0

You can have a look into https://github.com/fjogeleit/yaml-update-action/issues/428. The solution should be similar in your case.

```
propertyPath: 'services["my-service"]["build-no"]'
```

**Comment by NabilCC** [comment]
Hi @fjogeleit 

Thank you for responding so quickly.

I can confirm that changing the property path to the following has fixed the issue:

```services["${{inputs.service}}"][build-no]```

**Comment by fjogeleit** [comment]
Thank you for confirming and thanks for using this action. So, I close this issue - let me know if you have any other feedback or issues.

**Comment by GoldenMouse** [comment]
@fjogeleit In my case I have the hypened element in the beginning. Doing this causes an error:

`propertyPath: '["helm-example"].image.tag'`  
Any tips?

**Comment by ttruong-dexcom** [comment]
Nevermind I was able to access using `.` in start:

`propertyPath: '.["helm-example"].image.tag'`

**Comment by younsl** [comment]
I found the solution. Please refer to https://github.com/fjogeleit/yaml-update-action/issues/567#issuecomment-2099794536.
