### ISSUE TITLE
Error: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by CindyXin8080** [fjogeleit/yaml-update-action#464]
Got below error when trying to update yaml file:

(node:2054) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by fjogeleit** [comment]
hey, thanks for reporting. Currently its just a warning and you can ignore it. I will have a look if I can solve it with an dependency update.

**Comment by fjogeleit** [comment]
I released a new version v0.7.1 with all available dependency updates. As far as I see the warning should be gone. If you encounter any issues let me know.
