### ISSUE TITLE
Support for GitHub Enterprise

### ISSUE THREAD

**Issue by haught** [fjogeleit/yaml-update-action#468]
I would like to use this with GitHub Enterprise, but it looks to be hardcoded to use https://api.github.com and https://uploads.github.com. Would it be possible to get an input argument to set the url for github?

**Comment by fjogeleit** [comment]
Thanks for your request. I will check how I can support enterprise as well.

**Comment by fjogeleit** [comment]
You can try the latest version v0.8.0 which has a new input value `githubAPI` to customize the GitHub API BaseURL.
