### ISSUE TITLE
Assignees & Reviewers

### ISSUE THREAD

**Issue by djthornton1212** [fjogeleit/yaml-update-action#473]
First let me say that this is a great Action. It has just about everything I need in my workflow. 

Have you given any consideration to adding a assignees and/or reviewers? That's the only piece I'm missing. 

I'll likely remove the createPR and just have it update the file then use `peter-evans/create-pull-request` so I can get that last bit of functionality.

**Comment by fjogeleit** [comment]
With version v0.9.0 you can configure assignees and reviewers for the optional pull request. I hope it does now all you need for your workflow

**Comment by djthornton1212** [comment]
Thank you! I'll be testing it today.

**Comment by djthornton1212** [comment]
That worked great. Thank you very much.
