### ISSUE TITLE
HttpError: Not Found

### ISSUE THREAD

**Issue by sonomirco** [fjogeleit/yaml-update-action#502]
Hi there, 
I am trying to use this action, I have set the step in this way.
![image](https://user-images.githubusercontent.com/57708659/192692519-4f1c58ec-cd21-473e-ba8b-b3d5845ea9f5.png)

But I have all the time the `HttpError: Not Found`.
I have the same error using your example, creating a branch and a PR.
https://github.com/fjogeleit/yaml-update-action#update-helm-chart-after-a-new-docker-image-was-build

Looking forward to your help.
Thanks.

**Comment by fjogeleit** [comment]
Hey, what is your default branch? If it’s main you have to configure it because for compatibility reason the default value is master

**Comment by sonomirco** [comment]
My default branch is main, so I tested adding `targetBranch: main` and `masterBranchName: main` but still an error.

![image](https://user-images.githubusercontent.com/57708659/192702626-3cb74162-45bb-4c8e-9be5-41fbc6e283f6.png)

**Comment by fjogeleit** [comment]
I think the branch name should be only lowercase. Can you check another branch name without uppercase letters

**Comment by sonomirco** [comment]
Ok, now is working ;)
![image](https://user-images.githubusercontent.com/57708659/192706421-25dab2a4-4721-4c90-93a1-27b25cd048ca.png)

Thanks for the help 👍

**Comment by fjogeleit** [comment]
Great, you are welcome
