### ISSUE TITLE
Change multiple variables

### ISSUE THREAD

**Issue by sonomirco** [fjogeleit/yaml-update-action#503]
Hi, 
is it possible to pass an array of paths and values?
Thanks.

**Comment by fjogeleit** [comment]
No but you can execute the action multiple times

**Comment by sonomirco** [comment]
I am using it into a matrix.
But modify multiple parameters could be a nice feature.

**Comment by fjogeleit** [comment]
so the amount of parameters differs per matrix?

**Comment by sonomirco** [comment]
No per run in the matrix I change one parameter but every time I commit and change the yaml file.
I was thinking; if I can do in one step and commit only once it was simpler.

**Comment by fjogeleit** [comment]
You can achieve this by setting updateFile true in all calls except the last and only commitChange true for the last one

**Comment by sonomirco** [comment]
The matrix is dynamic, it could run once or 3 times; it depends on the number of projects that have been changed.

**Comment by fjogeleit** [comment]
but in both cases would it be necassary to commiz ones per matrix

**Comment by sonomirco** [comment]
Yep,so I am implementing the use of a Python script where in a loop I can change the yaml file and at the end I'll make a commit change.

**Comment by ragrag** [comment]
@fjogeleit thank you for creating this great action.

do you have plans to add support for this anytime soon? would be really nice to update multiple yaml files that have the same propertyPath and value in a single action especially if you're working multiple apps

**Comment by fjogeleit** [comment]
I implemented a new version with the new `changes` input, which supports now multi value and multi file support in a single action call. You can check the README for details or checkout the test example: https://github.com/fjogeleit/yaml-update-action/blob/main/.github/workflows/test.yml#L74

**Comment by fjogeleit** [comment]
Xour JSON is invalid, the latest `,` is wrong

**Comment by ragrag** [comment]
ohh yes that was it,
thanks again!

**Comment by fjogeleit** [comment]
Okay, great. Then I close this issue.

**Comment by sonomirco** [comment]
@fjogeleit thanks for developing this!!!
