### ISSUE TITLE
fwature request  - Append to an array in yaml file?

### ISSUE THREAD

**Issue by jameslounds** [fjogeleit/yaml-update-action#517]
My use case requires me to add an item to an array in a yaml file. Is there any way I can do this with this?

**Comment by fjogeleit** [comment]
Should be possible with an jsonpath expression:

 `$.list[(@.length)]`

Should add a new item to your list. I did not test it but thats how its documented in jsonpath, which this action uses:

https://www.npmjs.com/package/jsonpath

**Comment by maxisam** [comment]
unfortunately this doesn't work. It seems like jsonpath doesn't allow you to select something that is not exist. 

`$.list[(@.length-1)]` will replace the last one successfully, but $.list[(@.length)] will do nothing.

**Comment by maxisam** [comment]
https://github.com/dchester/jsonpath/issues/170

**Comment by fjogeleit** [comment]
Thanks, I will check this, do you need this functionality as well?

**Comment by fjogeleit** [comment]
@maxisam @jameslounds I implemented a workaround to support list appends with the proposed jsonpath expressions:

```
$.list[(@.length)]
```

I added an unit test to ensure that it is now working:

https://github.com/fjogeleit/yaml-update-action/blob/main/__tests__/action.test.ts#L169

**Comment by fjogeleit** [comment]
You're welcome. Thanks for the feedback - let me know if you encounter any issue
