### ISSUE TITLE
Feature Request: if propertyPath does not already exist, do not create it

### ISSUE THREAD

**Issue by shay-ul** [fjogeleit/yaml-update-action#518]
Hey!
I wanted to ask for a simple feature that can help us a lot - "Update only" instead of "Update and create if property does not exist".
Right now, if propertyPath does not actually exist, this action will create the propery (and it's entire path!) with the new value. I want to be able to fail this action if the propery does not exist.

**Comment by fjogeleit** [comment]
Hey, I will have a look on it.

**Comment by shay-ul** [comment]
Thank you! this is awesome
