### ISSUE TITLE
feature request: json support

### ISSUE THREAD

**Issue by maxisam** [fjogeleit/yaml-update-action#520]
I know it sounds funny since the name of the tool is called yaml-update-action. But since I realize what you did was like converting yaml to json by using js-yaml, I think it should be easy for you to make it support json as well.

Thanks for the great tool!

**Comment by fjogeleit** [comment]
So, you basically want to update a JSON file instead of yaml?

**Comment by fjogeleit** [comment]
Okay, I will have a look

**Comment by fjogeleit** [comment]
With the latest release you can test the JSON support. If you update multiple files at once it is possible to mix YAML and JSON files if all files have a valid extension. If not you have to configure the used format with the new `format` property.

**Comment by maxisam** [comment]
Wow, you are amazing! Thanks!
