### ISSUE TITLE
creating unwanted quote

### ISSUE THREAD

**Issue by maxisam** [fjogeleit/yaml-update-action#525]
somehow it creates quote around  'on'. But it works fine for another path like "$.resources[(@.length)]"

This one works totally fine.

<img width="983" alt="image" src="https://user-images.githubusercontent.com/456807/202289152-4dfc4f55-1cc2-444f-8b05-10c46186ae8b.png">

```yml
 changes: |
            {
              ".github/workflows/worker-production-build.yml":{
                "$.on.workflow_dispatch.inputs.project.options[(@.length)]": "${{ env.PROJ_PATH }}"
              }
            }
```

**Comment by maxisam** [comment]
I figured out. I need `noCompatMode: true`

https://github.com/nodeca/js-yaml/blob/0d3ca7a27b03a6c974790a30a89e456007d62976/test/issues/0266.js#L16

Should we just set it as true? or create an option for it?

**Comment by fjogeleit** [comment]
It's fine for me to just enable it. Do you want to open a PR?

**Comment by fjogeleit** [comment]
@maxisam I had to add an input for it because of first issues in existing workflows. You can just enabled it with `noCompatMode` set to `true`
