### ISSUE TITLE
Action removes (wanted) quotes

### ISSUE THREAD

**Issue by shay-ul** [fjogeleit/yaml-update-action#527]
Hi,
we are facing issues on our CD pipeline due to #525 , #526 
All single/double quotes with he following values are being removed from our helm values file:
'Y', 'N', 'yes', 'no'
Is there any way to convert this behaviour to be set on a specific parameter? or to disable it with a specific parameter?
Thanks!

**Comment by shay-ul** [comment]
Update: also happens to regular double quotes - "

**Comment by fjogeleit** [comment]
I will implement an option, to configure it explizit

**Comment by fjogeleit** [comment]
I added a `noCompatMode` with default false, so  it should now behave as before without changes anything.
