### ISSUE TITLE
HttpError: You have exceeded a secondary rate limit

### ISSUE THREAD

**Issue by shay-ul** [fjogeleit/yaml-update-action#537]
Hi! 
We are using this action and enjoying it very much, but during our busy hours we sometimes get the following error (from this action):
`Error: HttpError: You have exceeded a secondary rate limit and have been temporarily blocked from content creation. Please retry your request again later.`

We have created a case with GitHub Support, and their answer was:
`The limits you are hitting are anti-abuse (secondary rate limits) designed to protect the availability of GitHub.com. The error often occurs when anonymous or unauthenticated requests originating from an IP address breach our rate limits`

I can't wrap my head around this since I don't believe this action runs "anonymous or unauthenticated" requests. As I see it, all requests from this action to GitHub API should work with the API Token supplied to this action, right?
Is there something in this action that can be considered "anonymous or unauthenticated" against the GitHub API, and maybe this is where I'm getting the API limit?

Thanks!

**Comment by fjogeleit** [comment]
Thanks for your feedback. I don't think that there is any request without authentication because everything goes over the github `Octokit` client which get the API Token in the constructor. I will check it but I don't think that I find something. Maybe do you do some git commands beforehand that are not authenticated?

**Comment by shay-ul** [comment]
@fjogeleit the error output comes directly from the action. We don't hit this limit anywhere else, only on this action is failing with this error, which is very strange. 
Secondary limits can also be hit when running authenticated requests, but the limit there is 5000 per hour (and highly doubt that we run 5000 requests per hour. Although it's our GitHub Machine User API Token, we are a small organization and we don't have many repositories and actions running).
I believe that if we would hit authenticated requests limits, we would had builds and actions failing at the same time on other repositories, but this is not the case. The only thing failing with this rate limit is this action.

 I would highly appreciate if you can check if this is something the action is running, but if you don't believe so - then we can close this.
Thanks!

**Comment by shay-ul** [comment]
the GitHub support team looked into this and it seems as if our Machine User is being rate limited for excessive PR creation, and they advise to wait at least 2 seconds between each Pull Request creation. I'm closing this issue as the issue is not originating from this action.
Thanks again!

**Comment by fjogeleit** [comment]
Thanks a lot for your feedback, good to know.
