### ISSUE TITLE
When checked out with different PATs, the action won't create a PR

### ISSUE THREAD

**Issue by shay-ul** [fjogeleit/yaml-update-action#538]
Hey there, I have seen some actions not creating PRs although the workflow run is successful. 
After investigating, I found out that the action was checked out with different credentials from the ones I stated in the action. 
Example:
```
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_1 }}

    - uses: fjogeleit/yaml-update-action@main
      with:
       ...
       ...
       ...
       token: ${{ secrets.PAT_2 }}
       createPR: true
       ...
       ...
```

When running such workflow, the expected outcome is to have PR created, however, the workflow runs successfully and no PR is being generated.

Not sure what can be done about it, maybe a mention in the README so other people won't stumble upon this :)

**Comment by shay-ul** [comment]
Scratch that, the issue was that I was checked out with a different PAT than the one I stated in the action. When this is the case, the action does nothing but shows succesful run.

**Comment by fjogeleit** [comment]
sorry for the late response, thanks for mentioning your issue and how to solve them. I want to work out some kind of troubleshooting and common issues and consider to add this there.
