### ISSUE TITLE
double quote

### ISSUE THREAD

**Issue by maxisam** [fjogeleit/yaml-update-action#543]
Is it possible to use double quote for yaml? It always update the quote format for the target yaml file.

**Comment by fjogeleit** [comment]
Do you have an example what you mean?

**Comment by maxisam** [comment]
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/456807/236906274-dc3ffd98-6ac7-4940-8608-4ad6189ce7ff.png">

**Comment by fjogeleit** [comment]
The underlying library supports an `quotingType` option. So in general its possible but has to be implemented in the action. Will have a look when I find some time.
