### ISSUE TITLE
Action is formatting YAML, stripping comments/whitespace and resolving variable references

### ISSUE THREAD

**Issue by Hbbb** [fjogeleit/yaml-update-action#547]
I have a large `pubspec.yaml` file for a flutter application that contains comments and variables. I'm using this action to increment the `version` of the app. 

I noticed in the commits that this action is stripping out all comments. It's also changing variables. For example
This
```yaml
rlly-name: &rlly_name 'rlly'
```

Becomes
```yaml
rlly-name: rlly
```

**Is there some way to have this action _only_ update the field I specified and apply no other formatting?**

Here's an example of the commit the action made:
![SCR-20230821-g26](https://github.com/fjogeleit/yaml-update-action/assets/3803272/636a25ff-77b7-4939-a88a-859086e0380e)

**Comment by fjogeleit** [comment]
Hey, as described in the readme, works this action  based on a lib which converts yaml to json, updates the values and converts them back to yaml.

this removes comments, spaces and changes other formatting. There is no way to change this without using another core lib which would support this. So, right now this is not possible.
