### ISSUE TITLE
Error due to value having hyphen when updating yaml file

### ISSUE THREAD

**Issue by vaibbavisk20** [fjogeleit/yaml-update-action#571]
`- name: Checkout AI Repository
              uses: actions/checkout@v3
              with:
                repository: owner/xyz
                path: airepo

      - name: Update 
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'xxx/xxxx/xxx/xxx/xxx.yaml'
          repository: owner/xyz
          masterBranchName: main
          commitChange: false
          changes: |
            {
              "approach_classifier.openai_settings.engine": "chat",
              "structured_query_nl_to_sql.openai_settings.engine": "chat",
              "structured_query_nl_to_sql.openai_settings.model_name": "gpt-35-turbo",
              "structured_final_answer_generation.openai_settings.engine": "chat",
              "unstructured_search_query_generation.openai_settings.engine": "chat",
              "unstructured_final_answer_generation.openai_settings.engine": "chat",
              "unstructured_final_answer_generation.openai_settings.model_name": "gpt-35-turbo",
              "embeddings.openai_settings.engine": "embedding",

            }
          workDir: airepo

      - name: Print out bot_config.yaml
        run: |
          Get-Content -Path ./xxx/xxx/xxx/xxx/xxx.yaml -TotalCount 165
        shell: pwsh
        working-directory: airepo`

Trying to execute this workflow to update a yaml file, all of the other updates work as expected except for the one's where the value is "gpt-35-turbo". Is there any work around for this?

**Comment by fjogeleit** [comment]
So the action does not fail but the value for `structured_query_nl_to_sql.openai_settings.model_name` and  `unstructured_final_answer_generation.openai_settings.model_name` or not updated?

Can you provide a basic example of your YAML file where this paths are available, so I can reproduce it?
