### ISSUE TITLE
Hey there, I am having the following error when trying to create a PR (Error: failed to create PR: HttpError: Not Found)

### ISSUE THREAD

**Issue by vaneri** [fjogeleit/yaml-update-action#572]
The files are being processed and properly patched but somehow, I am having an error that doesn't give much context.
Could someone provide some information?
I am using the latest version and the main version is also failing
Could it be related to some access rights that are missing at the token level? 

Thanks a lot for your help

**Comment by fjogeleit** [comment]
Hey, do you create a PR to the same repo which triggered the action or another one? This error indicates that the GitHub token has no permission to create a PR.

can you share your basic configuration of the action

**Comment by vaneri** [comment]
I do create a PR in the same repository
here is the test that I am currently trying out; everything is working up to the point of creating the PR. 

name: 'release me / maybe'
on:
  pull_request:
    branches:
      - main

jobs:
  test-update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@v0.14.0
        with:
          branch: deployment/v1.0.1
          targetBranch: main
          createPR: true
          title: 'chore: Bump Prod to v1.0.1'
          message: 'chore: Bump Prod to v1.0.1'
          token: ${{ secrets.GITHUB_TOKEN }}
          changes: |
            {
              "production.yaml": {
                "image.tag": "v1.0.1"
              },
              "uk.production.yaml": {
                "image.tag": "v1.0.1"
              }
            }

**Comment by PeacePES** [comment]
I encountered the same error as you did when I created a PR in the other repository. Defining the `masterBranchName` parameter solved the problem in my case.

```
uses: fjogeleit/yaml-update-action@v0.14.0
with:
  ...
  masterBranchName: main
  ...
```

**Comment by fjogeleit** [comment]
You might need to add permissions to your GitHub Token, you can try to add the content write permission:

```yaml
permissions:
  contents: write
```

Which should allow your token to create pull requests.

**Comment by vaneri** [comment]
> You might need to add permissions to your GitHub Token, you can try to add the content write permission:
> 
> ```yaml
> permissions:
>   contents: write
> ```
> 
> Which should allow your token to create pull requests.

Adding the permissions worked! Thanks!
