### ISSUE TITLE
Update during PR

### ISSUE THREAD

**Issue by Plork** [fjogeleit/yaml-update-action#578]
hey, I am trying to generate / update a yaml file as part of the on: pull_request workflow we have.

just no matter what I try I get the following:

```failed to create PR: Error: could not parse file with path ...```

even tho createPR is false

```
commitChange: true
    branch: bump-test
    noCompatMode: false
    quotingType: '
    force: false
    masterBranchName: master
    targetBranch: master
    githubAPI: https://api.github.com
    createPR: false
    updateFile: false
    labels: yaml-updates
    token: ***
    repository: testrepo
    workDir: .
    commitUserName: github-actions[bot]
    commitUserEmail: github-actions[bot]@users.noreply.github.com
```

I gave the following permissions to the workflow just to exclude that.

```
permissions:
  checks: write
  contents: write
  pull-requests: write
```

any good tips or hints?

**Comment by fjogeleit** [comment]
this error means that the file you referencing does not exist in the file system. So you are sure that you checkout the correct branch and have the file you want to change on your filesystem under the expected path.

**Comment by Plork** [comment]
Yeah I know it doesn't exist I am trying to create it ;)

just so this:

https://github.com/fjogeleit/yaml-update-action/blob/main/action.yml#L25

so need to specify a method I guess. Did not check what the default was.

**Comment by fjogeleit** [comment]
hm not sure if I understand correctly, this action will not create the YAML file. It will only modify an existing one.

**Comment by Plork** [comment]
Then I misunderstood the "method" makes sense now! I will "touch" a file before the action to solve that! thnx
