### ISSUE TITLE
Request for consistent release tag

### ISSUE THREAD

**Issue by mubarak-j** [fjogeleit/yaml-update-action#583]
Thank you for the awesome GitHub action, this solves a lot of common use cases for us. much appreciated!

I'm curious if the tag `v1` is meant to track the latest unbreaking change, at this time i.e. `v0.15.0`? if yes, is there a way to automate this tag/release process? 

It's risky to always follow the `main` branch as shown in examples and risk being stale if using a static tag like `v0.15.0`.

**Comment by fjogeleit** [comment]
hm sorry, I t hink I created the tag by mistake. As there is no v1.x release yet.

I could provide an v0.1 tag or similar if this would help

**Comment by fjogeleit** [comment]
I created the v0.1 tag which you can use.

**Comment by mubarak-j** [comment]
Thank you!

**Comment by andylolz** [comment]
I’m absolutely not suggesting you change this (given the `v0.1` tag is in the wild and in use) but… I think a common way to do this would be a `v0` tag, that points to the latest `v0.x.y` release.

I’d expect `v0.1` to point to the latest `v0.1.x` release, but that’s not what it does currently.

**Comment by fjogeleit** [comment]
right, `v0.1` is not really intuitive but as mentioned is it now already in use. The next release will be `v1.0.0` to start clean and be more consistent in tagging.
