### ISSUE TITLE
Remove tag `v1`

### ISSUE THREAD

**Issue by wkoot** [fjogeleit/yaml-update-action#584]
Please consider removing tag [v1](https://github.com/fjogeleit/yaml-update-action/releases/tag/v1), as it seems to be incorrectly tagged.
This breaks automatic update scripts, thinking that `v1` > `v0.15.0`.

**Comment by fjogeleit** [comment]
Will take a look, thanks for reporting

**Comment by fjogeleit** [comment]
removed

**Comment by fabianszabo** [comment]
Thanks for breaking our CI/CD pipeline LOL you can't just remove the current version like that.

**Comment by fabszabo** [comment]
Why would you break the semantic versioning?

**Comment by fjogeleit** [comment]
Sorry for the disruption but this action still has no stable release yet and the v1 was a mistake on my side.

**Comment by wkoot** [comment]
> Why would you break the semantic versioning? This broke a bunch of our workflows. You should have just continued with version 1.x instead of creating 0.15

Why do your workflows try to work with a release that was removed?
Most tools even offer the option to blacklist or opt-out of certain versions.
Regardless, there haven't been any issues since the `v1` tag was removed
