### ISSUE TITLE
Value not reflected in commit

### ISSUE THREAD

**Issue by mtweeman** [fjogeleit/yaml-update-action#587]
I use this action to include following changes:
```
    changes: {
    "charts/app-test/values.yaml": {
      "image.repository": "hajlesilesia/app-test"
    },
    "charts/app-test/values.yaml": {
      "image.tag": "1.31.2"
    },
    "charts/app-test/Chart.yaml": {
      "appVersion": "1.31.2"
    }
  }
```

The 1st one is not included. Works fine for 2nd and 3rd.
Any ideas what could be wrong? Should I use another syntax?

**Comment by fjogeleit** [comment]
Let take a look on this, not sure if the slash is the issue here, maybe that you are changing two properties of the same root object.

As workaround you could check if it works when you split the first call in a dedicated (second) action call.

**Comment by mtweeman** [comment]
You're right about slash, I updated the title to reflect the problem better.
I removed "image.tag" related lines and it successfully updated the value of "image.repository".

**Comment by mtweeman** [comment]
I just noticed that [this syntax](https://github.com/fjogeleit/yaml-update-action#change-a-yaml-multifile) works fine. No fixing needed in such case. Sorry for bothering you :)

**Comment by fjogeleit** [comment]
good to know but I will still check it out, so thanks for mention it anyway
