### ISSUE TITLE
Can `targetBranch` and `branch` default to `masterBranchName`?

### ISSUE THREAD

**Issue by Henry-Hiles** [fjogeleit/yaml-update-action#589]
If possible, can `targetBranch` and `branch` default to `masterBranchName` so I only need to set one value? Thanks.

**Comment by fjogeleit** [comment]
Will take a look, have to check if this could introduce a breaking change for existing users.

**Comment by Henry-Hiles** [comment]
AFAIK this shouldn't be breaking, as its only for the default. Its just helpful for those who are using `main` instead of `master` or something similar.

**Comment by fjogeleit** [comment]
Updated and released with v0.16.0
